title: CCF Conference Deadlines # (Maintained by @gitferry)
# email: greferry@gmail.com
description: Countdown timers to keep track of deadlines of conferences recommended by
author: Fangyu Gai

domain: "ccf-countdown.github.io"
baseurl: ""

twitter_username: gitferry
twitter_hashtag: ccf-conference
github_username: ccf-countdown
github_repo: ccf-countdown.github.io

markdown: kramdown
ga_id: UA-36274081-2

include: ['_pages']