title: CCF Conference Deadlines # (Maintained by @gitferry)
# email: greferry@gmail.com
description: Countdowns to '<a href="https://www.ccf.org.cn/xspj/jc/zh/xx/">CCF conference</a>' deadlines
author: Fangyu Gai

domain: "ccf-countdown.github.io"
baseurl: ""

twitter_username: gitferry
twitter_hashtag: ccf-conference
github_username: ccf-countdown
github_repo: ccf-countdown.github.io

markdown: kramdown
ga_id: UA-36274081-2

include: ['_pages']